version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: notification_redis
    ports:
      - "6379:6379"

  flask_app:
    build: .
    container_name: notification_flask
    command: python app.py
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://notification_redis:6379/0
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: notification_celery
    command: celery -A tasks worker --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://notification_redis:6379/0
    depends_on:
      - redis
