version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: notification_redis
    ports:
      - "6379:6379"

  flask_app:
    build: .
    container_name: notification_flask
    command: python api/app.py
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: notification_celery
    command: celery -A tasks worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
