apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-flask-app
  labels:
    app: notification-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-system
      tier: flask
  template:
    metadata:
      labels:
        app: notification-system
        tier: flask
    spec:
      containers:
        - name: flask-app
          image: lokeshdangi/notification_system_flask_app:latest
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-celery
  labels:
    app: notification-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-system
      tier: celery
  template:
    metadata:
      labels:
        app: notification-system
        tier: celery
    spec:
      containers:
        - name: celery-worker
          image: lokeshdangi/notification_system_celery_worker:latest
          command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
          env:
            - name: REDIS_HOST
              value: "redis"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-redis
  labels:
    app: notification-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-system
      tier: redis
  template:
    metadata:
      labels:
        app: notification-system
        tier: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: notification-flask-app
spec:
  selector:
    app: notification-system
    tier: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: notification-celery
spec:
  selector:
    app: notification-system
    tier: celery
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: notification-system
    tier: redis
  ports:
    - protocol: TCP
      port: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
